from .panel_chief import panel_chief
from .panel_subordinate_list import panel_subordinates_list
from .panel_tools_with_subordinate import panel_tools_with_subordinate
from .panel_task import panel_task
